name: '🐞 Bug Report'
description: Use this template to report a bug.
title: '[Bug]: <Brief Description>'
body:
  - type: textarea
    id: '3'
    attributes:
      label: Description
      description: Please provide a clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: '4'
    attributes:
      label: Screenshots (if applicable)
  - type: dropdown
    id: '2'
    attributes:
      label: Affected Browser
      options:
        - Firefox
        - Chrome
        - Safari
        - Brave
        - Microsoft Edge
        - Other
    validations:
      required: true
  - type: checkboxes
    id: '1'
    attributes:
      label: Checklist
      options:
        - label: 'Checked for similar issues'
          required: true
        - label: 'Willing to work on this issue (optional)'
          required: false
